//creatures.js

/*	"name":	"Goblin",
	"Special":	0,
	"Max Qty":	6,
	"Max Spells": 0,
	"Abbrev":	"Gob",
	"Description":	",
	"selectionUpperRange",
	"inUseCount"*/

const creatureSet=[ //This is formatted like this for simplicity purposes, making it easy to work with when changing in the future. 
	"Ghoul",
	0,
	4,
	0,
	"Gho",
	"Ghoul(0 attack, 3 defense. 3 body, 3 mind -- When the ghoul first appears, it trades places with the first hero it sees and their movement ends. The ghoul refocuses each turn by rolling a die to randomly select a hero within their line of site, trading places with them immediately. On the hero's turn they may then move if they choose. When the hero the ghoul focuses on moves, they roll one die. If they roll a 1 or 6, the ghoul again trades places with them.)",
	0,
	0,
	
	"XXXlin",
	0,
	6, 
	0,
	"Yay",
	"",
	0,
	0,
		
	"Rats",
	0,
	1,
	0,
	"Rts",
	"Rats(3 rats 1 attack, 1 defense, 1 body, 1 mind -- Rats can all go on one space if necessary, but can spread over multiple spaces if available. Initially, place to left and right of this space when viewing from door if space is available.)",
	0,
	0,

	"Orc",
	0,
	8,
	0,
	"Orc",
	"",
	0,
	0,

	"Skeleton",
	0,
	4,
	0,
	"Ske",
	"",
	0,
	0,

	"Zombie",
	0,
	4,
	0,
	"Zom",
	"",
	0,
	0,

	"Abomination",
	0,
	3,
	0,
	"Abo",
	"",
	0,
	0,

	"Gorgon",
	0,
	4,
	0,
	"Gor",
	"Gorgon(2 attack, 4 defend, 2 body, 1 mind, 5 move -- Each turn a gorgon can attack or put someone to sleep. If they put a hero to sleep, the hero remains asleep until rolling a 1 or a 6. On each turn, a hero may roll 1 die for each mind point. A hero who is asleep may not attack, defend, move, or perform any action. If a hero awakens at the beginning of their turn, they may continue the turn as normal.)",
	0,
	0,

	"Spider",
	0,
	2,
	0,
	"Spi",
	"Spider(2 attack, 2 defense, 3 body, 1 mind, 7 move -- Any time a spider does damage to a player that player loses their next turn and cannot attack or defend until after their next turn.)",
	0,
	0,

	"Beast",
	0,
	2,
	0,
	"Bea",
	"",
	0,
	0,

	"Mummy",
	0,
	3,
	0,
	"Mum",
	"",
	0,
	0,

	"Dread Warrior",
	0,
	4,
	5,
	"DW",
	" Dread Spells drawn from deck. Select randomly when casting.)",
	0,
	0,

	"Gargoyle",
	0,
	3,
	5,
	"Gar",
	" Dread Spells drawn from deck. Select randomly when casting.)",
	0,
	0,
	
	"Fire Demon",
	0,
	1,
	0,
	"FD",
	"(4 attack, 5 defend, 4 body, 4 mind, 5 move -- A fire demon may throw a flame in place of a normal attack. A thrown flame travels in a straight line, doing 3 damage to all heroes along its path. Each hero may roll defense dice to reduce this damage.)",
	0,
	0,

	"Replicant",
	0,
	1,
	0,
	"Rep",
	"(move 10 - att, def, mind, body equal to the first hero it sees. On each of its turns after that it randomly reassigns to any hero it can see.)",
	0,
	0
];
