//creatures.js

/*	"name":	"Goblin",
	"Special":	0,
	"Max Qty":	6,
	"Max Spells": 0,
	"Abbrev":	"Gob",
	"Description":	",
	"selectionUpperRange",
	"inUseCount"*/
/*
const creatureSet=[ //This is formatted like this for simplicity purposes, making it easy to work with when changing in the future. 
	"Ghoul",
	0,
	4,
	0,
	"Gho",
	"Ghoul(0 attack, 3 defense. 3 body, 3 mind -- When the ghoul first appears, it trades places with the first hero it sees and their movement ends. The ghoul refocuses each turn by rolling a die to randomly select a hero within their line of site, trading places with them immediately. On the hero's turn they may then move if they choose. When the hero the ghoul focuses on moves, they roll one die. If they roll a 1 or 6, the ghoul again trades places with them.)",
	0,
	0,
	
	"Goblin",
	0,
	6, 
	0,
	"Gob",
	"",
	0,
	0,
		
	"Rats",
	0,
	1,
	0,
	"Rts",
	"Rats(3 rats 1 attack, 1 defense, 1 body, 1 mind -- Rats can all go on one space if necessary, but can spread over multiple spaces if available. Initially, place to left and right of this space when viewing from door if space is available.)",
	0,
	0,

	"Orc",
	0,
	8,
	0,
	"Orc",
	"",
	0,
	0,

	"Skeleton",
	0,
	4,
	0,
	"Ske",
	"",
	0,
	0,

	"Zombie",
	0,
	4,
	0,
	"Zom",
	"",
	0,
	0,

	"Abomination",
	0,
	3,
	0,
	"Abo",
	"",
	0,
	0,

	"Gorgon",
	0,
	4,
	0,
	"Gor",
	"Gorgon(2 attack, 4 defend, 2 body, 1 mind, 5 move -- Each turn a gorgon can attack or put someone to sleep. If they put a hero to sleep, the hero remains asleep until rolling a 1 or a 6. On each turn, a hero may roll 1 die for each mind point. A hero who is asleep may not attack, defend, move, or perform any action. If a hero awakens at the beginning of their turn, they may continue the turn as normal.)",
	0,
	0,

	"Spider",
	0,
	2,
	0,
	"Spi",
	"Spider(2 attack, 2 defense, 3 body, 1 mind, 7 move -- Any time a spider does damage to a player that player loses their next turn and cannot attack or defend until after their next turn.)",
	0,
	0,

	"Beast",
	0,
	2,
	0,
	"Bea",
	"",
	0,
	0,

	"Mummy",
	0,
	3,
	0,
	"Mum",
	"",
	0,
	0,

	"Dread Warrior",
	0,
	4,
	5,
	"DW",
	" Dread Spells drawn from deck. Select randomly when casting.  If a Dread Warrior can reach heroes and has the option to cast spells or attack, roll a die and attack if odd, cast spell if even.)",
	0,
	0,

	"Gargoyle",
	0,
	3,
	5,
	"Gar",
	" Dread Spells drawn from deck. Select randomly when casting.)",
	0,
	0,
	
	"Fire Demon",
	0,
	1,
	0,
	"FD",
	"(4 attack, 5 defend, 4 body, 4 mind, 5 move -- A fire demon may throw a flame in place of a normal attack. A thrown flame travels in a straight line, doing 3 damage to all heroes along its path. Each hero may roll defense dice to reduce this damage.)",
	0,
	0,

	"Replicant",
	0,
	1,
	0,
	"Rep",
	"(move 10 - att, def, mind, body equal to the first hero it sees. On each of its turns after that it randomly reassigns to any hero it can see.)",
	0,
	0
];
*/



const creatureSet=[ //This is formatted like this for simplicity purposes, making it easy to work with when changing in the future. 
	"Ghoul",
	0,
	4,
	0,
	"Gho",
	"Ghoul(0 attack, 3 defense. 3 body, 3 mind -- When the ghoul first appears, it trades places with the first hero it sees and their movement ends. The ghoul refocuses each turn by rolling a die to randomly select a hero within their line of site, trading places with them immediately. On the hero's turn they may then move if they choose. When the hero the ghoul focuses on moves, they roll one die. If they roll a 1 or 6, the ghoul again trades places with them.)",
	0,
	0,
	
	"Bats",
	0,
	6,
	0,
	"Bat",
	"Bat(10 Move, 2 attack, 1 defense. 1 body, 1 mind -- These take the place of Goblins in spells --When attacking a bat, heroes reduce attack by 1 when using non-ranged weapons.)",
	0,
	0,
	
	"Banshee",
	0,
	4,
	0,
	"Ban",
	"Banshee(6 move, 2 attack, 1 defense. 2 body, 2 mind -- Heroes cannot use ranged attack against a Banshee.)",
	0,
	0,

	"Zombie Rats",
	0,
	4,
	0,
	"ZR",
	"Zombie Rats(4 move, 2 attack, 1 defense. 2 body, 1 mind)",
	0,
	0,
	
	"Mutant Lizard",
	0,
	8,
	0,
	"ML",
	"Mutant Lizard(8 move, 3 attack, 2 defense. 1 body, 2 mind. -- These take the place of Orcs in spells)",
	0,
	0,
	
	"Familiar",
	0,
	4,
	0,
	"Fam",
	"Familiar(8 move, 2 attack, 2 defense. 1 body, 4 mind -- These take the place of Skeletons in spells.)",
	0,
	0,
	
	"Terror",
	0,
	4,
	0,
	"Ter",
	"Terror(5 move, 3 attack, 2 defense. 2 body, 2 mind -- Any hero next to a Terror cannot move and are so full of feat that they may only attack at half strength(rounded up).)",
	0,
	0,
	
	"Draugr",
	0,
	4,
	0,
	"Drg",
	"Draugr(4 move, 2 attack, 3 defense. 2 body, 0 mind -- These take the place of Zombies for spells.)",
	0,
	0,
		
	"Ogre"
	0,
	4,
	0,
	"Ogr"
	"Ogre(6 move, 3 attack, 3 defense. 3 body, 1 mind)"
	0,
	0,
	
	"Basilisk",
	0,
	4,
	0,
	"Bas",
	"Basilisk(10 move, 3 attack, 3 defense. 2 body, 3 mind.)",
	0,
	0,
	
	"Water Elemental",
	0,
	4,
	0,
	"W E",
	"Water Elemental(5 move, 2 attack, 3 defense. 2 body, 3 mind -- The water elemental can spray a hero with water (their regular attack) up to 4 spaces away, even over other heros or creatures.)",
	0,
	0,
	
	"Spider",
	0,
	2,
	0,
	"Spi",
	"Spider(7 move, 2 attack, 2 defense, 3 body, 1 mind, 7 move -- Any time a spider does damage to a player that player loses their next turn and cannot attack or defend until after their next turn.)",
	0, 
	0,
	
	"Tendril",
	0,
	3,
	0,
	"Ten",
	"Tendril(0 move, 4 attack, 0 defense, 3 body, 0 mind -- A tendril attacks a random hero within the same room or on the space just outside a door or to either side.)",
	0,
	0,
	
	"Werewolf",
	0,
	4,
	0,
	"Wer",
	"Werewolf(7 move, 3 attack, 4 defense, 2 body, 3 mind -- Take the place of a Mummy in spells -- Any time a werewolf successfully damages a hero, that hero loses their next turn unless they roll a 1 or a 6. This is broken once the werewolf is dead.)",
	0,
	0,

	"Necromancer",
	0,
	4,
	0,
	"Nec",
	"Necromancer(4 move, 0 attack, 4 defense, 3 body, 4 mind -- Necromancers have the ability to summon a Terror, Zombie Rat, or Draugr each turn, chosen randomly. Roll 1 red die divided by 2 (rounded up) to see how many.)",
	0,
	0,
	
	"Witch",
	0,
	4,
	5,
	"Wit",
	"Witch(4 move, 3 attack, 4 defense, 3 body, 5 mind -- A witch has the choice to try to turn all heroes into frogs for one turn. If she does so, each hero may break the spell by rolling an odd number on a red die.)",
	0,
	0,
	
	"Vampire",
	0,
	4,
	5,
	"Vam",
	"Vampire(10 move, 4 attack, 5 defense, 3 body, 4 mind -- Any hero damaged by a vampire cannot attack on their next turn unless they roll a 1 or a 6.)",
	0,
	0,
	
	"Ice Demon",
	0,
	1,
	0,
	"Ice",
	"Ice Demon(5 move, 4 attack, 5 defend, 4 body, 4 mind -- An Ice Demon may use a freeze attack in place of a regular attack. A freeze attack randomly targets one hero in their site and sprays an icy blast at them, doing 3 damage and freezing them and any hero or monster along the path. A frozen hero or monster may try to shake off the cold (defend) to reduce the damage.)",
	0,
	0,
	
	"Replicant",
	0,
	1,
	0,
	"Rep",
	"(move 10 - att, def, mind, body equal to the first hero it sees. On each of its turns after that it randomly reassigns to any hero it can see.)",
	0,
	0
]

